[package]
name = "Rtweekend"
version = "0.1.0"
edition = "2024"

[dependencies]
minifb = { version = "0.28.0", default-features = false }
zune-jpeg = "0.5"


[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = false   # default false in release already, but explicit
